### ISSUE TITLE
Nota informativa-Equipo 4

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-4#1]
[NOTA INFORMATIVA EQUIPO 4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-4/files/9952975/NOTA.INFORMATIVA.EQUIPO.4.pdf)

**Comment by AmeliReyesHernandez** [comment]
19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
